manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: alleindrach
      url-base: https://github.com/alleindrach
  projects:
    - name: zmk-ps2
      remote: alleindrach
      revision: alleindrach/touch_point
      import: app/west.yml
      path: zmk
    
  self:
    path: config
